apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configmappodrefreshers.k8slab.info
spec:
  group: k8slab.info
  scope: Namespaced
  names:
    plural: configmappodrefreshers
    singular: configmappodrefresher
    kind: ConfigMapPodRefresher
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: { }
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - namespace
                - config-map
                - owner-type
                - owner-name
              properties:
                namespace:
                  type: string
                config-map:
                  type: string
                owner-type:
                  type: string
                owner-name:
                  type: string
            status:
              type: object
              properties:
                phase:
                  type: string
      additionalPrinterColumns:
        - name: Namespace
          type: string
          jsonPath: .spec.namespace
        - name: ConfigMap
          type: string
          jsonPath: .spec.config-map
        - name: OwnerType
          type: string
          jsonPath: .spec.owner-type
        - name: OwnerName
          type: string
          jsonPath: .spec.owner-name