apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: swarms.k8slab.info
spec:
  group: k8slab.info
  scope: Namespaced
  names:
    plural: swarms
    singular: swarm
    kind: Swarm
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: { }
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - statefulset-name
                - configmap-name
                - workload
              properties:
                statefulset-name:
                  type: string
                configmap-name:
                  type: string
                version:
                  type: integer
                size:
                  type: integer
                workload:
                  type: array
                  items:
                    type: string
                members:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - jobs
                      - created_at
                    properties:
                      name:
                        type: string
                      created_at:
                        type: integer
                      jobs:
                        type: array
                        items:
                          type: string
                      state:
                        type: object
                        properties:
                          phase:
                            type: string
            status:
              type: object
              properties:
                phase:
                  type: string
      additionalPrinterColumns:
        - name: StatefulSet
          type: string
          jsonPath: .spec.statefulset-name
        - name: ConfigMap
          type: string
          jsonPath: .spec.configmap-name
        - name: Version
          type: integer
          jsonPath: .spec.version
        - name: Size
          type: integer
          jsonPath: .spec.size
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
        - name: Status
          type: string
          jsonPath: .status.phase